spring:
  application:
    name: ApiMonitor-Common
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/apimonitor?useUnicode=true&characterEncoding=utf8&serverTimezone=GMT%2B8&useSSL=false
    username: root
    password: Admin_!1
    hikari:
      minimum-idle: 5
      idle-timeout: 600000
      maximum-pool-size: 10
      auto-commit: true
      pool-name: MyHikariCP
      max-lifetime: 1800000
      connection-timeout: 30000
      connection-test-query: SELECT 1

server:
  port: 10081
  compression:
    enabled: true
    mime-types: application/json,application/xml,text/html,text/xml,text/plain
    ##默认情况下，仅会压缩2048字节以上的内容
    min-response-size: 2048
#mybatis start
mybatis:
  config-location: classpath:/mybatis-config.xml
#mybatis end